In [1]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("Social_Network_Ads.csv", header=0)

In [9]:
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [11]:
#data - pre-prcoessing 
#dealing wiht categorical columns 
df['Gender'].replace({'Male': 0, 'Female': 1}, inplace =True)

C:\Users\ANAND\AppData\Local\Temp\ipykernel_19448\211358643.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gender'].replace({'Male': 0, 'Female': 1}, inplace =True)
C:\Users\ANAND\AppData\Local\Temp\ipykernel_19448\211358643.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Gender'].replace({'Male': 0, 'Female': 1}, inplace =True)

In [15]:
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       0   19            19000          0
1  15810944       0   35            20000          0
2  15668575       1   26            43000          0
3  15603246       1   27            57000          0
4  15804002       0   19            76000          0